[package]
name = "opus_headers"
version = "0.1.0"
authors = ["Yannik BÃ¶ttcher <yannikboettcher@outlook.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
